### ISSUE TITLE
Missing display name when clicking a gene

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/GraphOmics#10]
```
Internal Server Error: /linker/get_ensembl_gene_info/25
Traceback (most recent call last):
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/explore_data_view.py", line 97, in get_ensembl_gene_info
    display_name = metadata['display_name'] if metadata is not None else ''
KeyError: 'display_name'
[25/Oct/2019 16:20:36] "GET /linker/get_ensembl_gene_info/25?id=YMR120C HTTP/1.1" 500 48904812
/Users/ronan/work/WebOmics/web_omics/linker/views/functions.py:779: FutureWarning:


.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated

/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/pandas/core/indexing.py:822: FutureWarning:


.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated

[25/Oct/2019 16:26:31] "GET /linker/get_ensembl_gene_info/25?id=YLR058C HTTP/1.1" 200 816
Internal Server Error: /linker/get_ensembl_gene_info/25
Traceback (most recent call last):
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/explore_data_view.py", line 97, in get_ensembl_gene_info
    display_name = metadata['display_name'] if metadata is not None else ''
KeyError: 'display_name'
[25/Oct/2019 16:27:00] "GET /linker/get_ensembl_gene_info/25?id=YBL002W HTTP/1.1" 500 48904817
[25/Oct/2019 16:27:06] "GET /linker/get_ensembl_gene_info/25?id=YMR116C HTTP/1.1" 200 894
```

**Comment by RonanDaly** [comment]
The trigger for this is clicking a gene - the associated information never shows up.
