### ISSUE TITLE
Group Analysis not working

### ISSUE THREAD

**Issue by RonanDaly** [glasgowcompbio/GraphOmics#28]
When a set up genes is selected and Goatools is run, there is no output. The console shows the following
```
Load GOEA Gene Ontology Analysis ...
fisher module not installed.  Falling back on scipy.stats.fisher_exact
  0%      0 of      0 population items found in association

Run GOEA Gene Ontology Analysis: current study set of 0 IDs ...
[04/Dec/2019 17:21:15] "POST /linker/get_gene_ontology/14 HTTP/1.1" 200 216
```
There are definitely genes selected.

**Comment by joewandy** [comment]
Found a new exception now
```
Load GOEA Gene Ontology Analysis ...
fisher module not installed.  Falling back on scipy.stats.fisher_exact
  0%      0 of      0 population items found in association

Run GOEA Gene Ontology Analysis: current study set of 0 IDs ...Internal Server Error: /app/linker/get_gene_ontology/120
Traceback (most recent call last):
  File "C:\Users\joewa\.virtualenvs\web_omics-MAkc_z5X\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\joewa\.virtualenvs\web_omics-MAkc_z5X\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\joewa\.virtualenvs\web_omics-MAkc_z5X\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\joewa\Work\git\WebOmics\web_omics\linker\views\explore_data_group.py", line 158, in get_gene_ontology
    df = goa.goea_analysis_df(selection_names)
  File "C:\Users\joewa\Work\git\WebOmics\web_omics\linker\views\gene_ontologies.py", line 35, in goea_analysis_df
    df = self._to_dataframe(goea_results_sig)
  File "C:\Users\joewa\Work\git\WebOmics\web_omics\linker\views\gene_ontologies.py", line 48, in _to_dataframe
    id_to_names = {v: k for k, v in self.names_to_id_dict.items()}
  File "C:\Users\joewa\Work\git\WebOmics\web_omics\linker\views\gene_ontologies.py", line 48, in <dictcomp>
    id_to_names = {v: k for k, v in self.names_to_id_dict.items()}
TypeError: unhashable type: 'dict'
django.request ERROR 2020-06-17 12:19:50,811 log.py:228 | Internal Server Error: /app/linker/get_gene_ontology/120
Traceback (most recent call last):
  File "C:\Users\joewa\.virtualenvs\web_omics-MAkc_z5X\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\joewa\.virtualenvs\web_omics-MAkc_z5X\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\joewa\.virtualenvs\web_omics-MAkc_z5X\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\joewa\Work\git\WebOmics\web_omics\linker\views\explore_data_group.py", line 158, in get_gene_ontology
    df = goa.goea_analysis_df(selection_names)
  File "C:\Users\joewa\Work\git\WebOmics\web_omics\linker\views\gene_ontologies.py", line 35, in goea_analysis_df
    df = self._to_dataframe(goea_results_sig)
  File "C:\Users\joewa\Work\git\WebOmics\web_omics\linker\views\gene_ontologies.py", line 48, in _to_dataframe
    id_to_names = {v: k for k, v in self.names_to_id_dict.items()}
  File "C:\Users\joewa\Work\git\WebOmics\web_omics\linker\views\gene_ontologies.py", line 48, in <dictcomp>
    id_to_names = {v: k for k, v in self.names_to_id_dict.items()}
TypeError: unhashable type: 'dict'
[17/Jun/2020 12:19:50] "POST /app/linker/get_gene_ontology/120 HTTP/1.1" 500 76804
```

**Comment by joewandy** [comment]
Fixed the above, but now I also encounter the same issue 

```
Load GOEA Gene Ontology Analysis ...
fisher module not installed.  Falling back on scipy.stats.fisher_exact
  0%      0 of  8,083 population items found in association
Run GOEA Gene Ontology Analysis: current study set of 85 IDs ...  0%      0 of     85 study items found in association
100%     85 of     85 study items found in population(8083)
Calculating 0 uncorrected p-values using fisher_scipy_stats
```

This gene set used to work before. I think we broke something along the way.

**Comment by joewandy** [comment]
The input dictionaries to GO analysis were not correct due to commit #https://github.com/glasgowcompbio/WebOmics/commit/473ecce219b8980a971e095faeaf651f62aea1ef that changed how pickled data was loaded.

Fixed now in commit #https://github.com/glasgowcompbio/WebOmics/commit/bafb398ac29cb47b104fd9a5f99ac46e0bc95baf.
