### ISSUE TITLE
Metabolomics Analysis Upload Doesn't Work

### ISSUE THREAD

**Issue by RonanDaly** [glasgowcompbio/GraphOmics#33]
While uploading metabolomics data from PiMP or standard format
[ArchiveStandard.zip](https://github.com/joewandy/WebOmics/files/4251131/ArchiveStandard.zip)
.

```Internal Server Error: /linker/upload_analysis
Traceback (most recent call last):
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/create_analysis_view.py", line 59, in form_valid
    species_list, metabolic_pathway_only)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/create_analysis_view.py", line 125, in get_data
    results, species_list, current_user, metabolic_pathway_only)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/functions.py", line 234, in save_analysis
    user=current_user)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/db/models/query.py", line 420, in create
    obj = self.model(**kwargs)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/db/models/base.py", line 501, in __init__
    raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))
TypeError: Analysis() got an unexpected keyword argument 'user'
```

**Comment by RonanDaly** [comment]
Not working with a different error
```Internal Server Error: /linker/upload_analysis
Traceback (most recent call last):
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/create_analysis_view.py", line 59, in form_valid
    species_list, metabolic_pathway_only)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/create_analysis_view.py", line 125, in get_data
    results, species_list, current_user, metabolic_pathway_only)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/functions.py", line 269, in save_analysis
    cluster_json = get_clusters(analysis_data, k)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/functions.py", line 288, in get_clusters
    json_data = to_clustergrammer(X_std, design_df)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/functions.py", line 332, in to_clustergrammer
    calc_cat_pval=False, run_enrichr=run_enrichr, enrichrgram=enrichrgram)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/clustergrammer/__init__.py", line 99, in cluster
    enrichrgram=enrichrgram)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/clustergrammer/make_clust_fun.py", line 20, in make_clust
    df = run_filter.df_filter_col_sum(df, threshold)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/clustergrammer/run_filter.py", line 56, in df_filter_col_sum
    df['mat'] = grab_df_subset(df['mat'], inst_rows, inst_cols)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/clustergrammer/run_filter.py", line 74, in grab_df_subset
    df = df.ix[keep_rows]
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'
```

**Comment by joewandy** [comment]
See issue #35
