### ISSUE TITLE
Type Error when uploading analyses

### ISSUE THREAD

**Issue by RonanDaly** [glasgowcompbio/GraphOmics#37]
When uploading an analysis, the following stack trace occurs.
```
Internal Server Error: /linker/upload_analysis
Traceback (most recent call last):
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/create_analysis_view.py", line 59, in form_valid
    species_list, metabolic_pathway_only)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/create_analysis_view.py", line 125, in get_data
    results, species_list, current_user, metabolic_pathway_only)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/functions.py", line 269, in save_analysis
    cluster_json = get_clusters(analysis_data, k)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/functions.py", line 283, in get_clusters
    X_std, data_df, design_df = get_standardized_df(analysis_data, axis, pk_cols=IDS)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/functions.py", line 303, in get_standardized_df
    X_std = inference.standardize_df(inference.data_df, log=True, axis=axis)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/pipelines.py", line 58, in standardize_df
    if np.all(data_arr >= 0) and log:
TypeError: '>=' not supported between instances of 'str' and 'int'
```
Might have something to do with display of data?

**Comment by joewandy** [comment]
Need data to reproduce the problem

**Comment by RonanDaly** [comment]
Use the ArchiveStandard.zip data

**Comment by joewandy** [comment]
I tried with that data, but I can't seem to reproduce the problem. It uploaded just fine.

**Comment by RonanDaly** [comment]
Not happening anymore, very strange. Boxplot is still not showing though, I'll put in a separate one for that.
