### ISSUE TITLE
Error running PALS analysis with PiMP data

### ISSUE THREAD

**Issue by RonanDaly** [glasgowcompbio/GraphOmics#38]
When performing a PALS analysis, the following error occurs.
```Internal Server Error: /linker/inference/pals/20
Traceback (most recent call last):
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/inference_view.py", line 522, in inference_pals
    pals_df = run_pals(pals_data_source, plage_weight, hg_weight)
  File "/Users/ronan/work/WebOmics/web_omics/linker/views/pathway_analysis.py", line 78, in run_pals
    pathway_df = pals.get_pathway_df(standardize=False)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/pals/PALS.py", line 51, in get_pathway_df
    activity_df = self.get_plage_activity_df(measurement_df, standardize)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/pals/PALS.py", line 82, in get_plage_activity_df
    activity_df = self._calculate_pathway_activity_df(measurement_df)
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/pals/PALS.py", line 278, in _calculate_pathway_activity_df
    activity_df = pd.DataFrame(pathway_activities).set_index([0])
  File "/Users/ronan/.local/share/virtualenvs/web_omics-VCzYizAw/lib/python3.7/site-packages/pandas/core/frame.py", line 4391, in set_index
    raise KeyError("None of {} are in the columns".format(missing))
KeyError: 'None of [0] are in the columns'
[26/Feb/2020 15:02:48] "POST /linker/inference/pals/20 HTTP/1.1" 500 50982811
```

**Comment by joewandy** [comment]
Need data to reproduce the problem

**Comment by RonanDaly** [comment]
This only occurs with PiMP upload data and when either ChEBI or KEGG compounds are selected. The following stack trace shows the setup.
```2020-02-26 15:31:38.825 | DEBUG    | pals.feature_extraction:__init__:42 - Using ChEBI as database
2020-02-26 15:31:38.825 | DEBUG    | pals.feature_extraction:get_database:111 - Retrieving data for Mus musculus from Reactome ChEBI metabolic_pathway_only=True
2020-02-26 15:31:39.759 | DEBUG    | pals.feature_extraction:__init__:55 - Mapping pathway to unique ids
2020-02-26 15:31:39.762 | DEBUG    | pals.feature_extraction:__init__:69 - Creating dataset to pathway mapping
2020-02-26 15:31:39.794 | DEBUG    | pals.feature_extraction:__init__:97 - Computing unique id counts
2020-02-26 15:31:39.812 | INFO     | linker.views.pathway_analysis:run_pals:76 - Running PALS with plage_weight=5 hg_weight=1
2020-02-26 15:31:39.816 | DEBUG    | pals.PALS:get_plage_activity_df:79 - Mean values of the rows in the DF is [-0. -0.  0.  0. -0. -0. -0. -0.  0.  0. -0. -0. -0.  0.  0. -0. -0. -0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0. -0.  0. -0.  0. -0. -0.
  0.  0. -0. -0.  0.  0. -0.  0.  0. -0.  0.  0.  0. -0.  0.  0. -0.  0.
  0. -0.  0. -0. -0.  0.  0.  0. -0.  0.  0.  0. -0. -0.  0.  0. -0. -0.
 -0. -0.  0.  0. -0. -0. -0.  0.  0. -0. -0. -0. -0. -0.  0.  0.  0.  0.
 -0.  0.  0. -0.  0.  0. -0.  0.  0.  0.  0.  0. -0.  0.  0.  0.  0. -0.
 -0.  0.  0. -0.  0.  0. -0.  0. -0.  0.  0. -0.  0.  0. -0.  0. -0. -0.
  0. -0. -0. -0. -0. -0.  0.  0.  0.  0. -0.  0. -0. -0.  0.  0.  0.  0.
  0. -0. -0.  0.  0.  0.  0. -0.  0. -0. -0.  0.  0. -0. -0. -0. -0.  0.
 -0.  0. -0.  0. -0.  0.  0.  0.  0.  0. -0.  0. -0. -0.  0.  0.  0. -0.
  0. -0. -0.  0. -0. -0.  0.  0. -0. -0. -0.  0. -0. -0.  0. -0. -0.  0.
  0. -0.  0.  0. -0. -0. -0. -0.  0.  0.  0. -0. -0.  0.  0. -0. -0. -0.
  0.  0. -0.  0. -0.  0. -0. -0. -0. -0.  0. -0. -0.  0. -0.  0. -0.  0.
  0.  0.  0.  0.  0.  0.  0. -0. -0. -0.  0.  0. -0.  0. -0. -0. -0. -0.
  0. -0. -0. -0.  0.  0. -0.  0. -0.  0. -0. -0. -0.  0.  0.  0. -0. -0.
 -0. -0.  0. -0. -0. -0.  0. -0.  0.  0.  0.  0. -0. -0.  0. -0.  0.  0.
  0.  0.  0. -0.  0. -0. -0. -0. -0. -0.  0. -0.  0.  0.  0. -0. -0. -0.
  0.  0.  0. -0.  0. -0. -0.  0. -0. -0.  0. -0.  0.  0.  0.  0.  0.  0.
 -0.  0.  0.  0.  0. -0.  0.  0. -0. -0. -0. -0. -0. -0.  0.  0. -0. -0.
  0. -0.  0.  0. -0. -0. -0.  0.  0.  0. -0. -0. -0. -0.  0.  0.]
2020-02-26 15:31:39.819 | DEBUG    | pals.PALS:get_plage_activity_df:80 - Variance in the rows of the DF is [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
```
It then freezes here and then the stack trace comes.

**Comment by RonanDaly** [comment]
Use the Archive.zip file, with the pimp data.

**Comment by joewandy** [comment]
Fixed by removing the peak id suffix from the indices of the intensity dataframe before feeding it into PALS.
